import type { Metadata } from 'next'
import { Footer } from '@/ui'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'РГК Афродита',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  )
}
